basePath: /
host: localhost:4000
info:
  contact: {}
  description: This is book store API built using Go and httprouter
  title: Book Store API
  version: "1.0"
paths:
  /api/users/{id}:
    get:
      consumes:
      - application/json
      description: Returns a single user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: User found
          schema:
            type: string
        "404":
          description: User not found
          schema:
            type: string
      summary: Get user by ID
      tags:
      - users
swagger: "2.0"
