basePath: /
definitions:
  main.ErrorResponse:
    properties:
      error:
        type: string
    type: object
host: localhost:4000
info:
  contact: {}
  description: This is book store API built using Go and httprouter
  title: Book Store API
  version: "1.0"
paths:
  /v1/healthcheck:
    get:
      description: Returns an object that include environment and status of the API
      produces:
      - application/json
      responses:
        "200":
          description: OK" "Response body
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Health Check The API
      tags:
      - Healthcheck
swagger: "2.0"
